# Generated by Django 5.1.7 on 2025-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='event_posters/')),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('participation_limit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('networking', 'Networking'), ('competition', 'Competition'), ('social', 'Social Event'), ('academic', 'Academic Talk'), ('sports', 'Sports Event'), ('career', 'Career Fair'), ('volunteer', 'Volunteering Event'), ('cultural', 'Cultural Festival'), ('club_meeting', 'Club Meeting'), ('research', 'Research Symposium'), ('hackathon', 'Hackathon'), ('orientation', 'Orientation Program')], max_length=20)),
                ('fees', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
