# Generated by Django 5.1.7 on 2025-03-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
